GET http://localhost:3000

### SEND FETCH SONGS REQUEST
GET http://localhost:3000/songs

### Find SONGS REQUEST
GET http://localhost:3000/songs/1

### Create New SONGS REQUEST
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZHlAZ21haWwuY29tIiwidXNlcklkIjo3LCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQ3MDU1OTA1LCJleHAiOjE3NDcxNDIzMDV9.Cupwzj4aT24QNKbNbAH07H4mUDilu5mAXZO7TZ3Wqy0

{
"title": "Ouuuu",
"artists": [0],
"releasedDate": "2022-09-29",
"duration": "02:34",
"lyrics": "Ouuuu nsitou li nseni"
}


### Update SONGS REQUEST
PUT http://localhost:3000/songs/1

### Update SONGS REQUEST
DELETE http://localhost:3000/songs/1

### Signup User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "john",
"lastName": "doe",
"email": "john2@gmail.com",
"password": "123456"
}


### Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "john@gmail.com",
"password": "123456"
}

###Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZlZHlAZ21haWwuY29tIiwidXNlcklkIjo3LCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQ3MDU1OTA1LCJleHAiOjE3NDcxNDIzMDV9.Cupwzj4aT24QNKbNbAH07H4mUDilu5mAXZO7TZ3Wqy0

### Artist Login User
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "fedy@gmail.com",
"password": "123456"
}

### Sign Up Artist
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"firstName": "Fedy",
"lastName": "Nouri",
"email": "fedy@gmail.com",
"password": "123456"
}